#!/bin/bash

xdef="$HOME/.XResources"

colors=( $( sed -re '/^!/d; /^$/d; /^#/d; s/(\*color)([0-9]):/\10\2:/g;' $xdef | grep 'color[01][0-9]:' | sort | sed  's/^.*: *//g' ) )

echo -e "\033[1;37m 
 Black    Red      Green    Yellow   Blue     Magenta   Cyan    White   
──────────────────────────────────────────────────────────────────────\033[0m"
for i in {0..7}; do echo -en "\033[$((30+$i))m ${colors[i]} \033[0m"; done
echo
for i in {8..15}; do echo -en "\033[1;$((22+$i))m ${colors[i]} \033[0m"; done
echo -e "\n"
